apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint-ms-1
  labels:
    app: checkpoint-ms-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkpoint-ms-1
  template:
    metadata:
      labels:
        app: checkpoint-ms-1
    spec:
      containers:
      - name: checkpoint-ms-1
        #image: nginx:latest
        imagePullPolicy: Always 
        image: liorruslander/checkpoint-ms-1-dev:1.0
        ports:
        #- containerPort: 80
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: checkpoint-service
spec:
  selector:
    app: checkpoint-ms-1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkpoint-ms-1
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: checkpoint-service
            port:
              number: 80